ALTER TABLE request DROP CONSTRAINT chk_request_type;
ALTER TABLE request ADD CONSTRAINT chk_request_type
    CHECK (type IN ('CLIENT_CREATE', 'UPDATE_BALANCE_PESSIMISTIC', 'UPDATE_BALANCE_OPTIMISTIC', 'OTHER'));
